<a href="https://colab.research.google.com/github/Shubham-Paudel/LAB-AI/blob/main/mobile_recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [70]:
import numpy as np
import pandas as pd
import random

In [343]:
mobile = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Datasets/mrs.csv')

In [344]:
mobile.head()

name  ratings    price  \
0  REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2    23999   
1        OPPO F11 Pro (Aurora Green, 128 GB)      4.5  ₹20,999   
2     REDMI Note 11 (Starburst White, 64 GB)      4.2    13149   
3     OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1    21999   
4        APPLE iPhone 13 mini (Blue, 128 GB)      4.6     3537   

                                              imgURL  \
0  https://rukminim2.flixcart.com/image/312/312/x...   
1  https://rukminim2.flixcart.com/image/312/312/k...   
2  https://rukminim2.flixcart.com/image/312/312/x...   
3  https://rukminim2.flixcart.com/image/312/312/x...   
4  https://rukminim2.flixcart.com/image/312/312/k...   

                                              corpus  
0  Storage128 GBRAM6  SystemAndroid 12Processor T...  
1  Storage128 GBRAM6 GBExpandable Storage256GB  S...  
2  Storage64 GBRAM4  SystemAndroid 11Processor Sp...  
3  Storage256 GBRAM12  SystemAndroid Q 11Processo...  
4  Storage128  SystemiOS 15Processor TypeA15 Bion...

In [345]:
mobile['corpus']

0       Storage128 GBRAM6  SystemAndroid 12Processor T...
1       Storage128 GBRAM6 GBExpandable Storage256GB  S...
2       Storage64 GBRAM4  SystemAndroid 11Processor Sp...
3       Storage256 GBRAM12  SystemAndroid Q 11Processo...
4       Storage128  SystemiOS 15Processor TypeA15 Bion...
                              ...                        
2540    Storage128 GBRAM8  SystemAndroid 10Processor S...
2541    Storage128 GBRAM8  SystemAndroid 11Processor S...
2542                                        not available
2543    Storage256 GBRAM12  SystemAndroid 12Processor ...
2544    Storage128 GBRAM6  SystemAndroid 13Processor T...
Name: corpus, Length: 2545, dtype: object

In [347]:
mobile['corpus'] = mobile['corpus'].str.lower()

In [348]:
mobile['corpus']

0       storage128 gbram6  systemandroid 12processor t...
1       storage128 gbram6 gbexpandable storage256gb  s...
2       storage64 gbram4  systemandroid 11processor sp...
3       storage256 gbram12  systemandroid q 11processo...
4       storage128  systemios 15processor typea15 bion...
                              ...                        
2540    storage128 gbram8  systemandroid 10processor s...
2541    storage128 gbram8  systemandroid 11processor s...
2542                                        not available
2543    storage256 gbram12  systemandroid 12processor ...
2544    storage128 gbram6  systemandroid 13processor t...
Name: corpus, Length: 2545, dtype: object

In [349]:
mobile = mobile[['name','ratings','price','imgURL','corpus']]

In [350]:
mobile

name  ratings    price  \
0             REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2    23999   
1                   OPPO F11 Pro (Aurora Green, 128 GB)      4.5  ₹20,999   
2                REDMI Note 11 (Starburst White, 64 GB)      4.2    13149   
3                OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1    21999   
4                   APPLE iPhone 13 mini (Blue, 128 GB)      4.6     3537   
...                                                 ...      ...      ...   
2540      SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)      4.2    27440   
2541                OnePlus 9 5G (Astral Black, 128 GB)      3.9    30203   
2542                                       Motorola a50      4.1     1549   
2543  SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...      4.3    20463   
2544                  vivo T2x 5G (Aurora Gold, 128 GB)      4.4    13999   

                                                 imgURL  \
0     https://rukminim2.flixcart.com/image/312/312/x...   
1     https://rukminim2.flixcart.com/image/312/312/k...   
2     https://rukminim2.flixcart.com/image/312/312/x...   
3     https://rukminim2.flixcart.com/image/312/312/x...   
4     https://rukminim2.flixcart.com/image/312/312/k...   
...                                                 ...   
2540  https://rukminim2.flixcart.com/image/312/312/x...   
2541  https://rukminim2.flixcart.com/image/312/312/x...   
2542  https://rukminim2.flixcart.com/image/312/312/k...   
2543  https://rukminim2.flixcart.com/image/312/312/x...   
2544  https://rukminim2.flixcart.com/image/312/312/x...   

                                                 corpus  
0     storage128 gbram6  systemandroid 12processor t...  
1     storage128 gbram6 gbexpandable storage256gb  s...  
2     storage64 gbram4  systemandroid 11processor sp...  
3     storage256 gbram12  systemandroid q 11processo...  
4     storage128  systemios 15processor typea15 bion...  
...                                                 ...  
2540  storage128 gbram8  systemandroid 10processor s...  
2541  storage128 gbram8  systemandroid 11processor s...  
2542                                      not available  
2543  storage256 gbram12  systemandroid 12processor ...  
2544  storage128 gbram6  systemandroid 13processor t...  

[2545 rows x 5 columns]

In [351]:
mobile['ratings'].value_counts()

ratings
4.3    583
4.2    514
4.4    422
4.5    318
4.1    242
4.6    152
4.0    105
4.7     87
3.9     62
3.8     22
3.7     11
3.6      5
3.0      4
3.5      4
2.9      4
3.3      4
3.1      3
5.0      2
4.8      1
Name: count, dtype: int64

In [352]:
mobile['corpus'].isnull()
mobile.isnull()

name  ratings  price  imgURL  corpus
0     False    False  False   False   False
1     False    False  False   False   False
2     False    False  False   False   False
3     False    False  False   False   False
4     False    False  False   False   False
...     ...      ...    ...     ...     ...
2540  False    False  False   False   False
2541  False    False  False   False   False
2542  False    False  False   False   False
2543  False    False  False   False   False
2544  False    False  False   False   False

[2545 rows x 5 columns]

In [353]:
mobile['name']

0               REDMI Note 12 Pro 5G (Onyx Black, 128 GB)
1                     OPPO F11 Pro (Aurora Green, 128 GB)
2                  REDMI Note 11 (Starburst White, 64 GB)
3                  OnePlus Nord CE 5G (Blue Void, 256 GB)
4                     APPLE iPhone 13 mini (Blue, 128 GB)
                              ...                        
2540        SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)
2541                  OnePlus 9 5G (Astral Black, 128 GB)
2542                                         Motorola a50
2543    SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...
2544                    vivo T2x 5G (Aurora Gold, 128 GB)
Name: name, Length: 2545, dtype: object

In [354]:
def Convert(string):
    return (string.split(","))

mobile['corpus']=mobile['corpus'].apply(Convert)
mobile['corpus']

0       [storage128 gbram6  systemandroid 12processor ...
1       [storage128 gbram6 gbexpandable storage256gb  ...
2       [storage64 gbram4  systemandroid 11processor s...
3       [storage256 gbram12  systemandroid q 11process...
4       [storage128  systemios 15processor typea15 bio...
                              ...                        
2540    [storage128 gbram8  systemandroid 10processor ...
2541    [storage128 gbram8  systemandroid 11processor ...
2542                                      [not available]
2543    [storage256 gbram12  systemandroid 12processor...
2544    [storage128 gbram6  systemandroid 13processor ...
Name: corpus, Length: 2545, dtype: object

In [355]:
mobile

name  ratings    price  \
0             REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2    23999   
1                   OPPO F11 Pro (Aurora Green, 128 GB)      4.5  ₹20,999   
2                REDMI Note 11 (Starburst White, 64 GB)      4.2    13149   
3                OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1    21999   
4                   APPLE iPhone 13 mini (Blue, 128 GB)      4.6     3537   
...                                                 ...      ...      ...   
2540      SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)      4.2    27440   
2541                OnePlus 9 5G (Astral Black, 128 GB)      3.9    30203   
2542                                       Motorola a50      4.1     1549   
2543  SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...      4.3    20463   
2544                  vivo T2x 5G (Aurora Gold, 128 GB)      4.4    13999   

                                                 imgURL  \
0     https://rukminim2.flixcart.com/image/312/312/x...   
1     https://rukminim2.flixcart.com/image/312/312/k...   
2     https://rukminim2.flixcart.com/image/312/312/x...   
3     https://rukminim2.flixcart.com/image/312/312/x...   
4     https://rukminim2.flixcart.com/image/312/312/k...   
...                                                 ...   
2540  https://rukminim2.flixcart.com/image/312/312/x...   
2541  https://rukminim2.flixcart.com/image/312/312/x...   
2542  https://rukminim2.flixcart.com/image/312/312/k...   
2543  https://rukminim2.flixcart.com/image/312/312/x...   
2544  https://rukminim2.flixcart.com/image/312/312/x...   

                                                 corpus  
0     [storage128 gbram6  systemandroid 12processor ...  
1     [storage128 gbram6 gbexpandable storage256gb  ...  
2     [storage64 gbram4  systemandroid 11processor s...  
3     [storage256 gbram12  systemandroid q 11process...  
4     [storage128  systemios 15processor typea15 bio...  
...                                                 ...  
2540  [storage128 gbram8  systemandroid 10processor ...  
2541  [storage128 gbram8  systemandroid 11processor ...  
2542                                    [not available]  
2543  [storage256 gbram12  systemandroid 12processor...  
2544  [storage128 gbram6  systemandroid 13processor ...  

[2545 rows x 5 columns]

In [356]:
mobile['imgURL']=mobile['imgURL'].apply(Convert)

In [357]:
mobile['price']=mobile['price'].apply(Convert)

In [358]:
mobile['mobile_name'] = mobile['name']

In [359]:
mobile['mobile_name'] = mobile['mobile_name'].str.strip()

In [360]:
mobile['mobile_name']

0               REDMI Note 12 Pro 5G (Onyx Black, 128 GB)
1                     OPPO F11 Pro (Aurora Green, 128 GB)
2                  REDMI Note 11 (Starburst White, 64 GB)
3                  OnePlus Nord CE 5G (Blue Void, 256 GB)
4                     APPLE iPhone 13 mini (Blue, 128 GB)
                              ...                        
2540        SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)
2541                  OnePlus 9 5G (Astral Black, 128 GB)
2542                                         Motorola a50
2543    SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...
2544                    vivo T2x 5G (Aurora Gold, 128 GB)
Name: mobile_name, Length: 2545, dtype: object

In [361]:
mobile['tags']=mobile['price']+mobile['corpus']

In [362]:
mobile

name  ratings       price  \
0             REDMI Note 12 Pro 5G (Onyx Black, 128 GB)      4.2     [23999]   
1                   OPPO F11 Pro (Aurora Green, 128 GB)      4.5  [₹20, 999]   
2                REDMI Note 11 (Starburst White, 64 GB)      4.2     [13149]   
3                OnePlus Nord CE 5G (Blue Void, 256 GB)      4.1     [21999]   
4                   APPLE iPhone 13 mini (Blue, 128 GB)      4.6      [3537]   
...                                                 ...      ...         ...   
2540      SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)      4.2     [27440]   
2541                OnePlus 9 5G (Astral Black, 128 GB)      3.9     [30203]   
2542                                       Motorola a50      4.1      [1549]   
2543  SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...      4.3     [20463]   
2544                  vivo T2x 5G (Aurora Gold, 128 GB)      4.4     [13999]   

                                                 imgURL  \
0     [https://rukminim2.flixcart.com/image/312/312/...   
1     [https://rukminim2.flixcart.com/image/312/312/...   
2     [https://rukminim2.flixcart.com/image/312/312/...   
3     [https://rukminim2.flixcart.com/image/312/312/...   
4     [https://rukminim2.flixcart.com/image/312/312/...   
...                                                 ...   
2540  [https://rukminim2.flixcart.com/image/312/312/...   
2541  [https://rukminim2.flixcart.com/image/312/312/...   
2542  [https://rukminim2.flixcart.com/image/312/312/...   
2543  [https://rukminim2.flixcart.com/image/312/312/...   
2544  [https://rukminim2.flixcart.com/image/312/312/...   

                                                 corpus  \
0     [storage128 gbram6  systemandroid 12processor ...   
1     [storage128 gbram6 gbexpandable storage256gb  ...   
2     [storage64 gbram4  systemandroid 11processor s...   
3     [storage256 gbram12  systemandroid q 11process...   
4     [storage128  systemios 15processor typea15 bio...   
...                                                 ...   
2540  [storage128 gbram8  systemandroid 10processor ...   
2541  [storage128 gbram8  systemandroid 11processor ...   
2542                                    [not available]   
2543  [storage256 gbram12  systemandroid 12processor...   
2544  [storage128 gbram6  systemandroid 13processor ...   

                                            mobile_name  \
0             REDMI Note 12 Pro 5G (Onyx Black, 128 GB)   
1                   OPPO F11 Pro (Aurora Green, 128 GB)   
2                REDMI Note 11 (Starburst White, 64 GB)   
3                OnePlus Nord CE 5G (Blue Void, 256 GB)   
4                   APPLE iPhone 13 mini (Blue, 128 GB)   
...                                                 ...   
2540      SAMSUNG Galaxy S20 FE 5G (Cloud Navy, 128 GB)   
2541                OnePlus 9 5G (Astral Black, 128 GB)   
2542                                       Motorola a50   
2543  SAMSUNG Galaxy S22 Ultra 5G (Phantom Black, 25...   
2544                  vivo T2x 5G (Aurora Gold, 128 GB)   

                                                   tags  
0     [23999, storage128 gbram6  systemandroid 12pro...  
1     [₹20, 999, storage128 gbram6 gbexpandable stor...  
2     [13149, storage64 gbram4  systemandroid 11proc...  
3     [21999, storage256 gbram12  systemandroid q 11...  
4     [3537, storage128  systemios 15processor typea...  
...                                                 ...  
2540  [27440, storage128 gbram8  systemandroid 10pro...  
2541  [30203, storage128 gbram8  systemandroid 11pro...  
2542                              [1549, not available]  
2543  [20463, storage256 gbram12  systemandroid 12pr...  
2544  [13999, storage128 gbram6  systemandroid 13pro...  

[2545 rows x 7 columns]

In [363]:
new_df=mobile[['mobile_name','tags']]
new_df['tags'] =new_df['tags'].apply(lambda x: " ".join(x))
new_df.head()

<ipython-input-363-1d1c6b6637ef>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] =new_df['tags'].apply(lambda x: " ".join(x))


mobile_name  \
0  REDMI Note 12 Pro 5G (Onyx Black, 128 GB)   
1        OPPO F11 Pro (Aurora Green, 128 GB)   
2     REDMI Note 11 (Starburst White, 64 GB)   
3     OnePlus Nord CE 5G (Blue Void, 256 GB)   
4        APPLE iPhone 13 mini (Blue, 128 GB)   

                                                tags  
0  23999 storage128 gbram6  systemandroid 12proce...  
1  ₹20 999 storage128 gbram6 gbexpandable storage...  
2  13149 storage64 gbram4  systemandroid 11proces...  
3  21999 storage256 gbram12  systemandroid q 11pr...  
4  3537 storage128  systemios 15processor typea15...

In [364]:
def Convert(string):
    li = string.lower()
    return li

In [365]:
new_df['mobile_name']=new_df['mobile_name'].str.lower()

<ipython-input-365-ac761216a13d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['mobile_name']=new_df['mobile_name'].str.lower()


In [366]:
new_df.head(20)

mobile_name  \
0           redmi note 12 pro 5g (onyx black, 128 gb)   
1                 oppo f11 pro (aurora green, 128 gb)   
2              redmi note 11 (starburst white, 64 gb)   
3              oneplus nord ce 5g (blue void, 256 gb)   
4                 apple iphone 13 mini (blue, 128 gb)   
5                  apple iphone 6s plus (gold, 64 gb)   
6              redmi 10 power (sporty orange, 128 gb)   
7               infinix hot 11 (emerald green, 64 gb)   
8         infinix note 10 pro (nordic secret, 256 gb)   
9                  samsung galaxy a04 (green, 128 gb)   
10                    vivo z1pro (sonic black, 64 gb)   
11                   moto c plus (pearl white, 16 gb)   
12                    oppo a15 (dynamic black, 32 gb)   
13    samsung galaxy z flip4 5g (bora purple, 128 gb)   
14              realme gt 2 pro (paper green, 256 gb)   
15            oneplus 9 pro 5g (morning mist, 256 gb)   
16        apple iphone 14 plus ((product)red, 256 gb)   
17                                               a10e   
18  xiaomi 11t pro 5g hyperphone (celestial magic,...   
19          redmi 10 prime 2022 (astral white, 64 gb)   

                                                 tags  
0   23999 storage128 gbram6  systemandroid 12proce...  
1   ₹20 999 storage128 gbram6 gbexpandable storage...  
2   13149 storage64 gbram4  systemandroid 11proces...  
3   21999 storage256 gbram12  systemandroid q 11pr...  
4   3537 storage128  systemios 15processor typea15...  
5   5537 storage64  systemios 9processor typea9 ch...  
6   18996 storage128 gbram8  systemandroid 13proce...  
7   9999 storage64 gbram4 gbexpandable storage256g...  
8   16999 storage256 gbram8 gbexpandable storage25...  
9   12999 storage128 gbram4 gbtotal memory128gb  s...  
10  15990 storage64 gbram4 gbexpandable storage256...  
11  6999 storage16 gbram2 gbexpandable storage32gb...  
12  ₹10 990 storage32 gbram3 gbexpandable storage2...  
13  24463 storage128 gbram8  systemandroid 12proce...  
14  7537 storage256 gbram12  systemandroid 12proce...  
15  15537 storage256 gbram12  systemandroid q 11pr...  
16  24463 storage256  systemios 16processor typea1...  
17                                 1299 not available  
18  31999 storage256 gbram8  systemandroid q 11pri...  
19  10990 storage64 gbram4  systemandroid q androi...

In [367]:
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

cv = CountVectorizer(max_features=5000,stop_words='english')
vector = cv.fit_transform(new_df['tags']).toarray()


print(vector)
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
def stem(text):
  y =[]

  for i in text.split():
    y.append(ps.stem(i))

  return " ".join(y)


new_df['tags']=new_df['tags'].apply(stem)
print(new_df)
similarity = cosine_similarity(vector)
sorted(list(enumerate(similarity[0])),reverse=True,key = lambda x: x[1])[1:6]
similarity[0]

[[0 2 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


<ipython-input-367-2d7ae0cce7a7>:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(stem)


                                            mobile_name  \
0             redmi note 12 pro 5g (onyx black, 128 gb)   
1                   oppo f11 pro (aurora green, 128 gb)   
2                redmi note 11 (starburst white, 64 gb)   
3                oneplus nord ce 5g (blue void, 256 gb)   
4                   apple iphone 13 mini (blue, 128 gb)   
...                                                 ...   
2540      samsung galaxy s20 fe 5g (cloud navy, 128 gb)   
2541                oneplus 9 5g (astral black, 128 gb)   
2542                                       motorola a50   
2543  samsung galaxy s22 ultra 5g (phantom black, 25...   
2544                  vivo t2x 5g (aurora gold, 128 gb)   

                                                   tags  
0     23999 storage128 gbram6 systemandroid 12proces...  
1     ₹20 999 storage128 gbram6 gbexpand storage256g...  
2     13149 storage64 gbram4 systemandroid 11process...  
3     21999 storage256 gbram12 systemandroid q 11pro...  
4

array([1.        , 0.24195563, 0.34299717, ..., 0.        , 0.22892448,
       0.57761553])

In [368]:

def recommend(name):
    name.lower() # make lowercase
    mobile_index = new_df[new_df["mobile_name"] == name].index[0]
    distances = similarity[mobile_index]
    mobile = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:7]
    for i in mobile:
        print(new_df.iloc[i[0]].mobile_name)


In [375]:
recommend('samsung galaxy j3 pro (gold, 16 gb)')

oppo a37f (grey, 16 gb)
samsung galaxy j7 (black, 16 gb)
redmi 3s (gold, 16 gb)
redmi 3s (silver, 16 gb)
redmi 3s (dark grey, 16 gb)
samsung galaxy j2 2018 (gold, 16 gb)


In [370]:
recommend('realme gt 2 pro (paper green, 256 gb)')

realme gt 2 pro (paper white, 256 gb)
realme gt 2 pro (paper green, 128 gb)
realme c35 (glowing black, 128 gb)
realme narzo 50 (speed blue, 128 gb)
realme gt neo 3 (150w - thor limited edition) (nitro blue, 256 gb)
realme gt neo 3 (150w) (sprint white, 256 gb)


In [371]:
recommend('oppo a15 (dynamic black, 32 gb)')

oppo a15 (mystery blue, 32 gb)
oppo a15 (dynamic black, 32 gb)
realme c21 (cross black, 64 gb)
oppo a54 (crystal black, 64 gb)
oppo a54 (starry blue, 128 gb)
oppo a54 (starry blue, 64 gb)


In [372]:
recommend('redmi 10 prime 2022 (astral white, 64 gb)')

redmi 10 prime 2022 (bifrost blue, 128 gb)
samsung galaxy m13 (stardust brown, 64 gb)
samsung galaxy m13 (midnight blue, 64 gb)
redmi 10 prime (phantom black, 64 gb)
redmi 10 prime (phantom black, 64 gb)
redmi 10 prime (bifrost blue, 64 gb)
